### ISSUE TITLE
Homepage Edits

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#1]
- [x] Navbar should be sticky

- [x] purple background behind twitter feed should be #83007e

- [x] Twitter feed and instagram feed should be separated. Instagram feed should be after products. Twitter feed after recipe.

- [x] Recipe section says Read More and Get Baking

- [x] Latest Buzz should pull featured image. Let's drop the body copy. 

- [x] Flavors should pull in featured image from products

- [x] Need to be able to place two logos in footer. How would you recommend? 

- [x] Brandon Grotesque not loading

**Comment by xtinarees** [comment]
@rickyferrer im seeing 'the buzz' featured images getting pulled in. Are you not? 
![screen shot 2016-04-24 at 9 44 14 pm](https://cloud.githubusercontent.com/assets/6852913/14772611/f37a6cbe-0a65-11e6-9c9d-cc31f206781b.png)

**Comment by xtinarees** [comment]
@rickyferrer if you dont see the images, can you let me know what operating system / browser version you're using?

**Comment by xtinarees** [comment]
@rickyferrer I added an example of how to add an image in the footer, just look at the footer menu in Appearance > Menus > Footer

**Comment by xtinarees** [comment]
basically, upload the images you want in the media library and link to them in the menu field

**Comment by rickyferrer** [comment]
I'm seeing images on Firefox and Safari, but not Chrome: Version 49.0.2623.112 (64-bit)
I'm on El Capitan 10.11.1

**Comment by rickyferrer** [comment]
![screen shot 2016-04-24 at 10 21 21 pm](https://cloud.githubusercontent.com/assets/9170979/14773094/50162b70-0a6b-11e6-8d4d-0fa91613ae52.png)

**Comment by xtinarees** [comment]
@rickyferrer can I make the header logo smaller when you scroll down? its so tall it takes up a lot of the page when the header is sticky

**Comment by rickyferrer** [comment]
I'll talk to client about it. Want to show her first though.
