### ISSUE TITLE
Recipe posts should feed into to specific Flavor pages

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#10]
For instance, there is a Banana Cream Pie recipe that uses the peanut butter chocolate cookie dough. I'd like that recipe to be on the Peanut Butter product page. I tagged the post with peanut-butter-chocolate, but if there is another way, let me know.

**Comment by xtinarees** [comment]
i'm going to add categories to do this bc they are easier to control than tags

**Comment by rickyferrer** [comment]
How do I do this?

**Comment by xtinarees** [comment]
@rickyferrer on the post there is a 'recipe type' field
