### ISSUE TITLE
Buttons on Product page

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#13]
One button will link to the store locator. The other button will link to an image in a lightbox (of a nutrition label)

![screen shot 2016-04-27 at 9 19 34 pm](https://cloud.githubusercontent.com/assets/9170979/14873619/240910ce-0cbe-11e6-9c8e-70c607047efd.png)

**Comment by xtinarees** [comment]
@rickyferrer what do you think about just showing the nutrition label below the button? like it slides in when you click the 'nutrition info' button? that would use less javascript and be simpler. lightboxes use more code that may slow down the site a bit, which may not be worth it for this one simple use case.

**Comment by rickyferrer** [comment]
And there's the room. Good.
