### ISSUE TITLE
import all locations into store locator

### ISSUE THREAD

**Issue by xtinarees** [xtinarees/sweet-lorens#15]

**Comment by rickyferrer** [comment]
I'm not seeing any stores in the store locator. Attached is the latest Excel file
[Store Finder 4.21.xlsx](https://github.com/xtinarees/sweet-lorens/files/244259/Store.Finder.4.21.xlsx)

**Comment by xtinarees** [comment]
thats bc I just added a bunch of new locations and easylocator is in the process of uploading all of them
