### ISSUE TITLE
Blog should should not limit number of posts shown. 

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#18]
Right now, it's limited to 9 with no pagination. I'd rather just show them all.

**Comment by xtinarees** [comment]
will there be a lot of posts? if there will be more than ~60 is then I need to add pagination, and the sorting cant be within the same page (if you click a sorting button, it would take you to a new page). If the number of blog posts will stay lower then I can keep it as is  (and take off the limit)

**Comment by xtinarees** [comment]
@rickyferrer

**Comment by rickyferrer** [comment]
Lets do 25 per page.
