### ISSUE TITLE
Contact Form on Contact Page

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#20]
Adding a contact page. Would like to have a form that has a field for name, email, dropdown of preselected inquiries (product, wholesale, question). and a field to write a comment.

**Comment by xtinarees** [comment]
I have used the contact form 7 plugin before. would you like for me to style this?

**Comment by rickyferrer** [comment]
Just installed it. Will have it up shortly. Then you can style it and I'll push the site live.

**Comment by rickyferrer** [comment]
ok. it's done: http://sweetlorens.com/testing/contact-us/
