### ISSUE TITLE
Our Story

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#4]
Need place to load image and link to video on backend. So it can look like this: https://invis.io/CU6VPDIKG#/140910242_SL-About

**Comment by rickyferrer** [comment]
Can we remove the padding left and right of Loren's picture so it can be larger?

**Comment by xtinarees** [comment]
@rickyferrer is the video already uploaded somewhere? if so could you send a link, and login info for that account?

**Comment by rickyferrer** [comment]
no, I don't have video yet.

**Comment by xtinarees** [comment]
I need the login to the account if you want to control the video on the site (play/ pause) but if it just plays on loop in the background, then just a link will work and I can just create a field

**Comment by xtinarees** [comment]
oh wait just kidding I dont need an account login I figured out another way to do it
