### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#6]
Need to add FAQ Page. I always like the way the VC FAQ is on Productions. Can we recreate here? Will be pulling copy from old site: http://sweetlorens.com/faqs/

**Comment by rickyferrer** [comment]
How do I use the accordion styling for this page?

**Comment by xtinarees** [comment]
just use the accordion page template

**Comment by xtinarees** [comment]
and then scroll to the bottom of the page and you'll see the fields
