### ISSUE TITLE
Paragraph spacing throughout

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/sweet-lorens#7]
This might be fixed once the fonts are loaded, but there doesn't seem to be any padding between paragraphs.

**Comment by rickyferrer** [comment]
There also doesn't seem to be any basic header hierarchy. Let me know if I need to design that.

**Comment by xtinarees** [comment]
@rickyferrer I added paragraph spacing, but it looks like in some posts like the recipe have added hard breaks that make the white space look a bit off. 
Also, I created some header styles just based off of the type used in other places on the site. I created an unpublished post called 'styleguide' so you could see what they look like. let me know if you want me to change any of those.

**Comment by rickyferrer** [comment]
The spacing looks good on the blog. Can we do the same throughout the site. ie. About page. http://sweetlorens.com/testing/about/
